const COUNTRY_CODES = {
  'Argentina':             'ar',
  'Alemanha':              'de',
  'Arábia Saudita':        'sa',
  'África do Sul':         'za',
  'Áustria':               'at',
  'Austrália':             'au',
  'Argélia':               'dz',
  'Bélgica':               'be',
  'Bósnia e Herzegovina':  'ba',
  'Brasil':                'br',
  'Cabo Verde':            'cv',
  'Canadá':                'ca',
  'Catar':                 'qa',
  'Colômbia':              'co',
  'Coreia do Sul':         'kr',
  'Costa do Marfim':       'ci',
  'Croácia':               'hr',
  'Curaçao':               'cw',
  'EUA':                   'us',
  'Equador':               'ec',
  'Egito':                 'eg',
  'Escócia':               'gb-sct',
  'Espanha':               'es',
  'França':                'fr',
  'Gana':                  'gh',
  'Haiti':                 'ht',
  'Holanda':               'nl',
  'Inglaterra':            'gb-eng',
  'Iraque':                'iq',
  'Irã':                   'ir',
  'Japão':                 'jp',
  'Jordânia':              'jo',
  'Marrocos':              'ma',
  'México':                'mx',
  'Nova Zelândia':         'nz',
  'Noruega':               'no',
  'Panamá':                'pa',
  'Paraguai':              'py',
  'Portugal':              'pt',
  'Rep. Dem. do Congo':    'cd',
  'Senegal':               'sn',
  'Suécia':                'se',
  'Suíça':                 'ch',
  'Tchéquia':              'cz',
  'Tunísia':               'tn',
  'Turquia':               'tr',
  'Uruguai':               'uy',
  'Uzbequistão':           'uz',
};

export function getFlagUrl(name) {
  const code = COUNTRY_CODES[name];
  return code ? `https://flagcdn.com/w40/${code}.png` : null;
}
